### ISSUE TITLE
LDAPS with SelfSigned Certificate

### ISSUE THREAD

**Issue by ansgarschulte** [mettke/ssh-key-authority#11]
Hi,

wenn I configure LDAPS which uses a SelfSigned Certificate, I run into trouble. I cannot sync down new Users.
Is there a way to configure the CA certificate in the PHP backend?
Thx

**Comment by mettke** [comment]
PHP is not able to disable trust or trust a specific certificate. Instead it uses the system configuration represented by the ldap.conf file.
Take a look at these:

- https://stackoverflow.com/questions/25424622/authenticating-a-self-signed-certificate-for-ldaps-connection
  Uses `TLS_REQCERT never` which might be insecure
- https://serverfault.com/questions/398684/ubuntu-12-04-ldap-ssl-self-signed-cert-not-accepted
  Uses `TLS_CACERT /etc/ssl/certs/cacert.crt` which requires a CA certificate

**Comment by mettke** [comment]
To make this a bit more comprehensible. You have to:
1.  Create an ldap.conf file with your preferred content
1.  Mount it into the ska-php container to /etc/ldap.conf

**Comment by ansgarschulte** [comment]
Thx! I google similar today and got it now working with a pem file instead of crt.
And I had to disable starttls = 0 in config.ini
