### ISSUE TITLE
Docker: config.ini not found or wrong permissions

### ISSUE THREAD

**Issue by astgjrst** [mettke/ssh-key-authority#16]
Hi,

we have tried to run your latest docker-container (https://hub.docker.com/r/toendeavour/ssh-key-authority/). 

We tried the following commands:

`docker pull toendeavour/ssh-key-authority`
`docker run toendeavour/ssh-key-authority`

![grafik](https://user-images.githubusercontent.com/65950221/83736507-046cf500-a652-11ea-9e16-5e73904a9475.png)

OS: Ubuntu 20.04
Docker-Version: 19.03.8

**Comment by mettke** [comment]
You may want to spend a second and take a look at the [examples](https://github.com/mettke/ssh-key-authority/tree/master/examples) folder. This application requires a configuration and if you do not supply it, it will have a hard time working :smirk:.

**Comment by astgjrst** [comment]
Deine Antworten auf die Probleme und deine Doku lassen echt zu wünschen übrig.
Ich mache es einfach selber, hätte ich die Zeit, die ich bisher zum debuggen benötigt habe, in etwas Eigenes gesteckt, wäre ich längst fertig und hätte nicht so viele Kopfschmerzen wie mit deinem Zeug. Wenigstes hast du immer sehr schnell geantwortet, auch wenn es nie was gebracht hat.

**Comment by mettke** [comment]
Well given that I'm doing this in my free time, I think I'm doing pretty good. Have fun with building your own :wink:.

Just a side note thou - this is not my documentation just like this is not my application. Its from https://github.com/operasoftware/ssh-key-authority. Maybe you get better answers there.
