### ISSUE TITLE
Any K8S deployment exemple?

### ISSUE THREAD

**Issue by strus38** [mettke/ssh-key-authority#18]
Hi

Trying to deploy this on a K8S cluster. Do you have anything that would be available?
Thanks!

**Comment by mettke** [comment]
I'm afraid I have not. 

You may, however, want to try whether converting one of the three `docker-compose.yml` examples works out for you.

* https://github.com/mettke/ssh-key-authority/tree/master/examples
* https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/
