### ISSUE TITLE
Upgrade from Original Source Opera Repo!

### ISSUE THREAD

**Issue by jilabaca** [mettke/ssh-key-authority#19]
Hello, do you have to have any consideration when migrating from the source code of the Opera repository?

**Comment by mettke** [comment]
Hey there,

I have two answers to your question:

The simple answer is: No, you can use the old database directly as everything will get migrated.

The detailed answer is: Yes. Make sure to think about:
1. Having a backup of the database, as you never know if there is an edge case that makes something fail
1. Testing the setup beforehand by creating a new server with a copy of the old database and to see whether it migrates successfully and whether you like the changes I made to this software
1. There is no going back. Once your database is migrated you cannot use it with the original version anymore. So make sure to think about the previous two points 

Other than that you should be good to go

**Comment by jilabaca** [comment]
Thank you very much for the information! and great job! with the product improvements! I will be attentive to new features of the software.
