### ISSUE TITLE
IP Address Check with ports

### ISSUE THREAD

**Issue by jaredkipe** [mettke/ssh-key-authority#2]
Hey there, I was wondering what you thought about the following modification?  Any side effects you can think of?

Essentially, there is a check and exception if a server has the same IP, but what if it is the same IP and different port, e.g. a docker container...

```
	echo date('c')." {$hostname}: Checking IP address {$server->ip_address}.\n";
	$matching_servers = $server_dir->list_servers(array(), array('ip_address' => $server->ip_address, 'key_management' => array('keys')));
	if(count($matching_servers) > 1) {
```

Checking port as well...
```
	echo date('c')." {$hostname}:{$server->port}: Checking IP address {$server->ip_address}.\n";
	$matching_servers = $server_dir->list_servers(array(), array('ip_address' => $server->ip_address, 'port' => $server->port, 'key_management' => array('keys')));
	if(count($matching_servers) > 1) {
```

**Comment by mettke** [comment]
That's a very good point. I guess you're using two different domains (one for server, one for container) with different ports and both resolve to the same ip. 

I'm not comfortable with simply circumventing the check. Instead I prefer creating two new flags 

* disable_ip_collision_protection
* allow_different_ports_on_single_ip

Please feel free to have a look at the commit and check whether it would solve your problem.

**Comment by jaredkipe** [comment]
I am using two different domains that resolve to the same IP address, technically they can resolve to a bunch of IP addresses as it is a kubernetes cluster with node port services that point to containers running SSH for deploying code. 

I would be fine, or rather I could/would like to support, having the same domain with different ports.

**Comment by jaredkipe** [comment]
Some of this would be straight up better if you could "name" the server something other than a domain name.  (a friendly name or display name)

**Comment by mettke** [comment]
Giving a server a custom name would be nice for sure. However, it won't be implemented in the current version. At the moment I'm building v3 and there it will be a feature.

**Comment by mettke** [comment]
Change was merged into master. Therefore this ticket seems fixed for me. Feel free to reopen it if you feel that this fix does not solve the problem you mentioned.
