### ISSUE TITLE
Add Public Key does not use baseurl

### ISSUE THREAD

**Issue by ansgarschulte** [mettke/ssh-key-authority#6]
I run ssh-key-authority behind a reverse proxy (traefik) with baseurl = https://mydomain.com/ssh-key-authority/

When I add a new public key the redirect points to https://mydomain.com but not the configured baseurl (=https://mydomain.com/ssh-key-authority/)

**Comment by mettke** [comment]
The patch should fix the issue. If it does not, please reopen the issue

(Docker Image will be available in about half an hour)

**Comment by ansgarschulte** [comment]
Hi, 
thx for the quick fix. 
Just saw that a click on the logo also uses wrong url..

**Comment by mettke** [comment]
In the new or old version? 'Cause that should be fixed too :wink:

**Comment by ansgarschulte** [comment]
Sorry. Had to Upgrade docker version. It is working. :-) THX

**Comment by ansgarschulte** [comment]
Ok, But "Explain" and "Sync Now" Button is still broken

**Comment by mettke** [comment]
try again in a few minutes (image is build atm)

**Comment by ansgarschulte** [comment]
Thx a lot

**Comment by ansgarschulte** [comment]
Hi, 
another one:
"Delete Public Key" does not work and redirects wrong domain without path

**Comment by mettke** [comment]
argh - stop finding bugs in this software :laughing: (I'm joking - thanks for the help - new version is ready soon)
